<?php

$helperPath = __DIR__ . '/../plugin/wp-agent-bridge/includes/class-takka-wordpress-bridge-integrity.php';
$bootstrapPath = __DIR__ . '/../plugin/wp-agent-bridge/takka-wordpress-bridge.php';
$identityPath = __DIR__ . '/../plugin/wp-agent-bridge/includes/class-takka-wordpress-bridge-direct-runtime-identity.php';
$guidancePath = __DIR__ . '/../plugin/wp-agent-bridge/includes/class-takka-wordpress-bridge-runtime-guidance.php';

$helper = file_get_contents($helperPath);
$bootstrap = file_get_contents($bootstrapPath);
$identity = file_get_contents($identityPath);
$guidance = file_get_contents($guidancePath);

if (!is_string($helper)) {
    fwrite(STDERR, "Integrity helper is missing.\n");
    exit(1);
}
if (!is_string($bootstrap)) {
    fwrite(STDERR, "Plugin bootstrap is missing.\n");
    exit(1);
}
if (!is_string($identity)) {
    fwrite(STDERR, "Direct Runtime identity helper is missing.\n");
    exit(1);
}
if (!is_string($guidance)) {
    fwrite(STDERR, "Runtime guidance generator is missing.\n");
    exit(1);
}

$requiredHelperMarkers = [
    "'/media-verify'",
    "'chunk_integrity'",
    "'wpab_direct_media_integrity_mismatch'",
    "'require_integrity'",
    "'expected_content_sha256'",
    "'expected_current_sha256'",
    "'expected_current_absent'",
    "'rest_request_before_callbacks'",
    "'rest_request_after_callbacks'",
    "'side_effects' => false",
    "['source_cleanup'] = false",
    "'theme_write_integrity_guard'",
    "'media_runtime_verify'",
];

foreach ($requiredHelperMarkers as $marker) {
    if (strpos($helper, $marker) === false) {
        fwrite(STDERR, "Integrity helper is missing marker: {$marker}\n");
        exit(1);
    }
}

if (strpos($bootstrap, "require_once __DIR__ . '/includes/class-takka-wordpress-bridge-integrity.php';") === false
    || strpos($bootstrap, 'TakKa_WordPress_Bridge_Integrity::init();') === false) {
    fwrite(STDERR, "Integrity helper is not registered by the plugin bootstrap.\n");
    exit(1);
}

// Runtime_Identity owns only machine identity. Operational integrity guidance
// must not migrate back into it, otherwise a later identity sync can overwrite
// the canonical guidance generated by Runtime_Guidance.
foreach ([
    '## Exact theme asset writes',
    'require_integrity=true',
    'expected_content_sha256',
    'expected_current_sha256',
    'expected_current_absent=true',
    'replace only the mismatched staged payload file(s)',
] as $forbiddenIdentityGuidance) {
    if (strpos($identity, $forbiddenIdentityGuidance) !== false) {
        fwrite(STDERR, "Runtime identity must not own integrity routing guidance: {$forbiddenIdentityGuidance}\n");
        exit(1);
    }
}
if (strpos($identity, "'guidance_owned_by' => TakKa_WordPress_Bridge_Runtime_Guidance::class") === false) {
    fwrite(STDERR, "Runtime identity does not declare Runtime_Guidance ownership.\n");
    exit(1);
}

// Runtime_Guidance stays concise and points model clients to the machine-readable
// capability contract; its failure policy must retain the targeted media-integrity
// recovery rule rather than recommending a transport switch or broad restaging.
foreach ([
    'RUNTIME_CAPABILITIES.json',
    'media integrity 409: replace only mismatched staging payloads when identifiable',
    'do not change transport blindly',
] as $requiredGuidanceMarker) {
    if (strpos($guidance, $requiredGuidanceMarker) === false) {
        fwrite(STDERR, "Runtime guidance is missing integrity fast-path marker: {$requiredGuidanceMarker}\n");
        exit(1);
    }
}

foreach ([$helperPath, $identityPath, $guidancePath, $bootstrapPath] as $path) {
    $source = file_get_contents($path);
    try {
        $tokens = token_get_all($source, TOKEN_PARSE);
    } catch (ParseError $e) {
        fwrite(STDERR, basename($path) . ' failed PHP parse validation: ' . $e->getMessage() . "\n");
        exit(1);
    }
    if (!is_array($tokens) || !$tokens) {
        fwrite(STDERR, basename($path) . " did not parse as PHP.\n");
        exit(1);
    }
}

echo "integrity-diagnostics-test: ok\n";
