<?php

$bytes = '';
for ($i = 0; $i < 41946; $i++) {
    $bytes .= chr(($i * 131 + 17) & 0xff);
}

$expectedBytes = strlen($bytes);
$expectedSha = hash('sha256', $bytes);
$binaryChunkBytes = 6000;
$payloads = [];

for ($offset = 0; $offset < $expectedBytes; $offset += $binaryChunkBytes) {
    $chunk = substr($bytes, $offset, $binaryChunkBytes);
    $encoded = base64_encode($chunk);
    $payloads[] = $encoded;
}

$rebuilt = '';
foreach ($payloads as $encoded) {
    $decoded = base64_decode($encoded, true);
    if ($decoded === false) {
        fwrite(STDERR, "Strict Base64 decode failed.\n");
        exit(1);
    }
    $rebuilt .= $decoded;
}

if (strlen($rebuilt) !== $expectedBytes) {
    fwrite(STDERR, "Rebuilt byte count mismatch.\n");
    exit(1);
}
if (!hash_equals($expectedSha, hash('sha256', $rebuilt))) {
    fwrite(STDERR, "Rebuilt SHA-256 mismatch.\n");
    exit(1);
}
if (count($payloads) !== 7) {
    fwrite(STDERR, "Unexpected payload count for 41,946-byte regression fixture.\n");
    exit(1);
}

$identity = file_get_contents(__DIR__ . '/../plugin/wp-agent-bridge/includes/class-takka-wordpress-bridge-direct-runtime-identity.php');
if (!is_string($identity)
    || strpos($identity, 'ChatGPT-local / conversation-uploaded files — preferred batched path') === false
    || strpos($identity, '/wp-agent-bridge-runtime/v1/media-upload') === false
    || strpos($identity, 'ordered `data_paths`') === false
    || strpos($identity, 'ONE tree/commit/ref update') === false
    || strpos($identity, 'Do not call media-verify first in the normal path') === false
    || strpos($identity, '`data_blob_shas`') === false
    || strpos($identity, '/wp-agent-bridge-media/v1/upload-chunk') === false
    || strpos($identity, 'Sequential chunk-command fallback') === false
    || strpos($identity, 'split the ORIGINAL BINARY') === false) {
    fwrite(STDERR, "Runtime identity guidance does not prefer the one-commit blob-SHA staged-media fast path with verify-on-error diagnostics.\n");
    exit(1);
}

foreach ([
    '## Canonical runtime fast path',
    'Migration signals are limited to:',
    'read `wordpress-bridge/RUNTIME_CONNECTION.json` FIRST',
    '`status=retired` or `do_not_use=true`',
    'If it contains `replaced_by`, go directly to that replacement repository',
    'If a usable GitHub write action is already visible, do not run connector discovery',
    'create `wordpress-bridge/commands/pending/<id>.json` immediately',
    'Resolution fast path: reuse this exact canonical repository/branch',
] as $needle) {
    if (strpos($identity, $needle) === false) {
        fwrite(STDERR, "Canonical runtime generator is missing fast-resolution marker: {$needle}\n");
        exit(1);
    }
}

$fast = file_get_contents(__DIR__ . '/../plugin/wp-agent-bridge/includes/class-takka-wordpress-bridge-direct-media-fast-path.php');
if (!is_string($fast)
    || strpos($fast, "array_key_exists('data_blob_shas', \$json)") === false
    || strpos($fast, 'read_blob_text') === false
    || strpos($fast, 'single-recursive-tree-read') === false
    || strpos($fast, 'snapshot_sources') === false
    || strpos($fast, 'chunk_integrity') === false
    || strpos($fast, 'transport_fast_path') === false
    || strpos($fast, 'git-blob-sha-direct') === false
    || strpos($fast, "\$upload['normal_flow_verify_first'] = false") === false
    || strpos($fast, "\$upload['automatic_for_staged_data_paths'] = true") === false
    || strpos($fast, "\$upload['preferred_publish_mode'] = 'single-inline-tree-commit-when-supported'") === false) {
    fwrite(STDERR, "Direct Runtime media blob-SHA fast path is incomplete.\n");
    exit(1);
}

$bootstrap = file_get_contents(__DIR__ . '/../plugin/wp-agent-bridge/takka-wordpress-bridge.php');
if (!is_string($bootstrap)
    || strpos($bootstrap, 'class-takka-wordpress-bridge-direct-media-fast-path.php') === false
    || strpos($bootstrap, 'TakKa_WordPress_Bridge_Direct_Media_Fast_Path::init()') === false) {
    fwrite(STDERR, "Media fast path is not loaded by the plugin bootstrap.\n");
    exit(1);
}

$guard = file_get_contents(__DIR__ . '/../plugin/wp-agent-bridge/includes/class-takka-wordpress-bridge-direct-onboarding-guard.php');
if (!is_string($guard)
    || strpos($guard, 'sync_identity_guidance_if_needed') === false
    || strpos($guard, 'IDENTITY_SYNC_VERSION_OPTION') === false
    || strpos($guard, 'IDENTITY_SYNC_RETRY') === false
    || strpos($guard, 'private const IDENTITY_SYNC_VERSION = 2;') === false
    || strpos($guard, 'TakKa_WordPress_Bridge_Direct_Runtime_Identity::sync()') === false
    || strpos($guard, '10 * MINUTE_IN_SECONDS') === false) {
    fwrite(STDERR, "Existing-runtime identity refresh guard is missing media-fast-path guidance resync.\n");
    exit(1);
}
if (strpos($guard, 'sync_resolution_guidance') !== false || strpos($guard, 'put_guidance_if_changed') !== false) {
    fwrite(STDERR, "Runtime guidance must be generated by Identity::sync(), not patched after generation.\n");
    exit(1);
}

$hardening = file_get_contents(__DIR__ . '/../plugin/wp-agent-bridge/includes/class-takka-wordpress-bridge-direct-hardening.php');
if (!is_string($hardening)
    || strpos($hardening, 'replace_runtime_webhook') === false
    || strpos($hardening, 'serialized_webhook') === false
    || strpos($hardening, 'PRIMARY_LOCK_OPTION') === false
    || strpos($hardening, 'TakKa_WordPress_Bridge_Direct_Runtime_V2::webhook($request)') === false
    || strpos($hardening, "'retryable' => true") === false) {
    fwrite(STDERR, "Direct Runtime primary webhook serialization hardening is missing.\n");
    exit(1);
}

echo "media-binary-chunk-staging-test: ok\n";
