<?php

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Prevent Direct Runtime from recursively reconciling an in-flight command on
 * webhook pushes that were generated by that command's own GitHub bookkeeping
 * or media staging/cleanup writes.
 */
final class TakKa_WordPress_Bridge_Direct_Webhook_Loop_Guard
{
    public static function init(): void
    {
        add_filter('rest_pre_dispatch', [self::class, 'pre_dispatch'], 5, 3);
    }

    public static function pre_dispatch($result, WP_REST_Server $server, WP_REST_Request $request)
    {
        if ($result !== null
            || strtoupper((string) $request->get_method()) !== 'POST'
            || (string) $request->get_route() !== TakKa_WordPress_Bridge_Direct_Runtime::WEBHOOK_ROUTE) {
            return $result;
        }

        if (strtolower(trim((string) $request->get_header('x-github-event'))) !== 'push') {
            return $result;
        }

        $raw = (string) $request->get_body();
        $signature = strtolower(trim((string) $request->get_header('x-hub-signature-256')));
        if (!TakKa_WordPress_Bridge_Direct_GitHub::verify_webhook($raw, $signature)) {
            return $result;
        }

        $payload = json_decode($raw, true);
        if (!is_array($payload)
            || ($payload['ref'] ?? '') !== 'refs/heads/' . TakKa_WordPress_Bridge_Direct_Runtime::RUNTIME_BRANCH
            || !empty($payload['deleted'])) {
            return $result;
        }

        $connection = TakKa_WordPress_Bridge_Direct_Runtime::connection();
        $repository_id = (int) ($payload['repository']['id'] ?? 0);
        $repository = isset($payload['repository']['full_name']) ? (string) $payload['repository']['full_name'] : '';
        $installation_id = (int) ($payload['installation']['id'] ?? 0);
        $private = isset($payload['repository']['private']) ? (bool) $payload['repository']['private'] : false;
        if (!$private
            || $repository_id < 1
            || $installation_id < 1
            || (int) ($connection['repository_id'] ?? 0) !== $repository_id
            || (int) ($connection['installation_id'] ?? 0) !== $installation_id
            || !hash_equals((string) ($connection['repository'] ?? ''), $repository)) {
            return $result;
        }

        $has_new_pending = false;
        $has_changes = false;
        $only_internal = true;
        foreach (($payload['commits'] ?? []) as $commit) {
            if (!is_array($commit)) {
                continue;
            }
            foreach (['added', 'modified', 'removed'] as $kind) {
                foreach (($commit[$kind] ?? []) as $path) {
                    if (!is_string($path) || $path === '') {
                        continue;
                    }
                    $has_changes = true;
                    if (($kind === 'added' || $kind === 'modified')
                        && preg_match('#^wordpress-bridge/commands/pending/[A-Za-z0-9._-]{1,120}\.json$#', $path)) {
                        $has_new_pending = true;
                    }
                    if (!preg_match('#^wordpress-bridge/(?:media/|results/|commands/completed/|commands/pending/)#', $path)) {
                        $only_internal = false;
                    }
                }
            }
        }

        if (!$has_changes || $has_new_pending || !$only_internal) {
            return $result;
        }

        return new WP_REST_Response([
            'ok' => true,
            'ignored' => true,
            'reason' => 'internal-runtime-write',
        ], 200);
    }
}
